### ISSUE TITLE
It does not work because forge jar changed place.

### ISSUE THREAD

**Issue by qouteall** [Runemoro/Devoldefy#1]
In the code the directory of forge jar is "{home_dir}/.gradle/caches/minecraft/net/minecraftforge/forge/{mc_version}-{forge_version}/{csv_type}/{csv_build}/forgeSrc-{mc_version}-{forge_version}.jar"
in newer forge version it's
"modding_project\build\fg_cache\net\minecraftforge\forge\1.13.2-25.0.191_mapped_snapshot_20180921-1.13".

**Comment by florensie** [comment]
oman pls to fix

**Comment by fadookie** [comment]
I was working on a fix for this here (still work in progress) https://github.com/fadookie/Devoldefy/commit/75b0d372bfa45180f5efb30218f27bacb0681a91

I was able to get it to download the forge jar from the new location, but the code in the output folder isn't being remapped. I'm giving up on this and doing my port by hand for now, but if anyone else wants to pick it up the code is there.

**Comment by fadookie** [comment]
Actually I found a better solution: the https://github.com/qouteall/Devoldefy which updates for more recent forge/MCP layout and adds reverse mapping capabilities.
There's currently a build error on master, but I put up a fixed version at https://github.com/fadookie/Devoldefy

**Comment by qouteall** [comment]
oops, I will fix my fork's compile error
